# Generated by Django 6.0.3 on 2026-03-26 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('montant_cotisation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequence', models.CharField(max_length=20)),
                ('date_debut', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('TERMINE', 'Terminé')], max_length=20)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembreGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_reception', models.IntegerField()),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likelemba_app.groupe')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paiement', models.DateField()),
                ('statut', models.CharField(choices=[('PAYE', 'Payé'), ('NON_PAYE', 'Non payé')], max_length=20)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likelemba_app.membregroupe')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tour', models.IntegerField()),
                ('date_tour', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('beneficiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likelemba_app.membregroupe')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='likelemba_app.groupe')),
            ],
        ),
    ]
