# Generated by Django 6.0.3 on 2026-03-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelemba_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='frequence',
            field=models.CharField(choices=[('QUOTIDIEN', 'Quotidien'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('ANNUEL', 'Annuel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('TERMINE', 'Terminé')], default='ACTIF', max_length=20),
        ),
    ]
