# Generated by Django 6.0.3 on 2026-04-23 00:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likelemba_app', '0002_groupe_date_creation_alter_groupe_frequence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membregroupe',
            unique_together={('utilisateur', 'groupe')},
        ),
    ]
