# Generated by Django 6.0.3 on 2026-04-23 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelemba_app', '0003_alter_membregroupe_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='membregroupe',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='membregroupe',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='membregroupe',
            name='groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='likelemba_app.groupe'),
        ),
    ]
