# Generated by Django 6.0.3 on 2026-04-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelemba_app', '0005_alter_membregroupe_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='beneficiaire',
            new_name='membre',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='numero_tour',
        ),
        migrations.AddField(
            model_name='tour',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYE', 'Payé')], default='EN_ATTENTE', max_length=20),
        ),
    ]
