# Generated by Django 6.0.3 on 2026-06-08 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelemba_app', '0006_rename_beneficiaire_tour_membre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='likelemba_app.tour'),
            preserve_default=False,
        ),
    ]
