# Generated by Django 6.0.3 on 2026-08-08 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelemba_app', '0007_paiement_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiviteRecente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MEMBRE', 'Nouveau membre'), ('COTISATION', 'Cotisation reçue'), ('TOUR', 'Tour terminé'), ('RETARD', 'Paiement en retard')], max_length=20)),
                ('titre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='likelemba_app.groupe')),
            ],
            options={
                'verbose_name': 'Activité récente',
                'verbose_name_plural': 'Activités récentes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
