# Generated by Django 6.0.3 on 2026-08-09 01:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likelemba_app', '0008_activiterecente'),
    ]

    operations = [
        migrations.AddField(
            model_name='membregroupe',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ActiviteRecente',
        ),
    ]
